spring.application.name=Api-para-ApiCall
spring.datasource.url=jdbc:postgresql://dpg-d4o28svdiees7380026g-a.oregon-postgres.render.com/atividade_individual_nk8m
spring.datasource.username=atividade_individual_nk8m_user
spring.datasource.password=H0XdZg1abLs93AKHZeG3ViXqqt456WSB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/FabLab/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true